-- Run this SQL to update the users table for the new dashboard features
ALTER TABLE `users`
ADD COLUMN `is_archived` TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN `is_distinguished` TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN `device` VARCHAR(255) DEFAULT NULL,
ADD COLUMN `browser` VARCHAR(255) DEFAULT NULL,
ADD COLUMN `location` VARCHAR(255) DEFAULT NULL,
ADD COLUMN `ip` VARCHAR(45) DEFAULT NULL,
ADD COLUMN `last_activity` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
